# Dependencies
markdown:         kramdown


# Permalinks
permalink:        pretty

# Setup
title:            Leila Alimehr
tagline:          ''
description:      ''
url:              http://leilaalimehr.github.io


github_username:  leilaalimehr
permalink: /:year/:month/:title.html
excerpt_separator: <!--more-->



# Dependencies
gems:                [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
